name: quant_trading
channels:
  - defaults
  - conda-forge
dependencies:
  - aom=3.6.0=h313beb8_0
  - blas=1.0=openblas
  - bottleneck=1.4.2=py311hb9f6ed7_0
  - brotli=1.1.0=h6caf38d_4
  - brotli-bin=1.1.0=h6caf38d_4
  - bullet-cpp=3.25=py311hca32420_4
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h191e429_0
  - contourpy=1.3.1=py311h48ca7d4_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=h80987f9_0
  - expat=2.7.1=h313beb8_0
  - ffmpeg=6.1.1=h7693a39_3
  - fontconfig=2.14.1=h6402c1e_3
  - fonttools=4.60.1=pyh7db6752_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gdk-pixbuf=2.42.10=h969f7ef_2
  - gettext=0.21.0=hbdbcc25_2
  - giflib=5.2.2=h80987f9_0
  - glib=2.84.2=hc880cf1_0
  - glib-tools=2.84.2=hc880cf1_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py311h5c1b81f_0
  - graphite2=1.3.14=hc377ac9_1
  - harfbuzz=10.2.0=he637ebf_1
  - icu=73.1=h313beb8_0
  - importlib-metadata=8.5.0=py311hca03da5_0
  - jinja2=3.1.6=py311hca03da5_0
  - jpeg=9f=h2f69dba_0
  - kiwisolver=1.4.8=py311h313beb8_0
  - lame=3.100=h1a28f6b_0
  - lcms2=2.16=he26ebf3_1
  - leptonica=1.82.0=hdedf53e_3
  - lerc=4.0.0=h313beb8_0
  - libabseil=20250127.0=cxx17_h313beb8_0
  - libarchive=3.8.1=h44a83c5_0
  - libavif=1.1.1=h80987f9_0
  - libbrotlicommon=1.1.0=h6caf38d_4
  - libbrotlidec=1.1.0=h6caf38d_4
  - libbrotlienc=1.1.0=h6caf38d_4
  - libcxx=20.1.8=h8869778_0
  - libdeflate=1.22=h80987f9_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.2=hdc2269c_0
  - libiconv=1.16=h80987f9_3
  - libogg=1.3.5=h1a28f6b_1
  - libopenblas=0.3.30=hf2bb037_0
  - libopus=1.3.1=h80987f9_1
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=5.29.3=h14f15fd_1
  - librsvg=2.56.3=h38920c8_2
  - libsqlite=3.50.4=hf8de324_0
  - libtheora=1.1.1=h1a28f6b_3
  - libtiff=4.7.0=h91aec0a_0
  - libtorch=2.5.1=gpu_mps_h7b1bc93_204
  - libuv=1.48.0=h80987f9_0
  - libvorbis=1.3.7=h1a28f6b_0
  - libvpx=1.13.1=h313beb8_0
  - libwebp=1.3.2=hf40cdb4_1
  - libwebp-base=1.3.2=h80987f9_1
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.8=h0b34f26_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=3.0.2=py311h80987f9_0
  - matplotlib=3.10.6=py311ha1ab1f8_0
  - matplotlib-base=3.10.6=py311h066045a_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py311hca03da5_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - networkx=3.5=py311hca03da5_0
  - nomkl=3.0=0
  - numexpr=2.11.0=py311h8c72970_1
  - numpy=2.0.1=py311he598dae_1
  - numpy-base=2.0.1=py311hfbfe69c_1
  - openh264=2.1.1=h98b2900_0
  - openjpeg=2.5.2=hba36e21_1
  - openssl=3.5.4=h5503f6c_0
  - opentelemetry-api=1.37.0=py311hca03da5_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py311h43d6402_0
  - pango=1.50.7=hf2328af_2
  - pcre2=10.42=hb066dcc_1
  - pillow=11.3.0=py311h6dd570d_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h09dc60e_0
  - pthread-stubs=0.4=hd74edd7_1002
  - pybullet=3.25=py311he9eb210_4
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.11.11=h89a136b_0_cpython
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytz=2025.2=py311hca03da5_0
  - readline=8.3=h0b18652_0
  - setuptools=78.1.1=py311hca03da5_0
  - six=1.17.0=py311hca03da5_0
  - sleef=3.5.1=h80987f9_2
  - sqlite=3.50.2=h79febb2_1
  - sympy=1.14.0=py311hca03da5_0
  - tesseract=5.2.0=h9e66425_3
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py311h80987f9_0
  - typing-extensions=4.15.0=py311hca03da5_0
  - typing_extensions=4.15.0=py311hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py311h80987f9_1
  - wheel=0.45.1=py311hca03da5_0
  - xorg-libx11=1.8.12=h6a5fb8c_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xorg-libxext=1.3.6=hd74edd7_0
  - xz=5.6.4=h80987f9_1
  - zipp=3.21.0=py311hca03da5_0
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - cloudpickle==3.1.1
      - farama-notifications==0.0.4
      - filelock==3.19.1
      - fsspec==2025.9.0
      - gymnasium==1.2.1
      - pygame==2.6.1
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
prefix: /Users/victor_he/miniconda3/envs/quant_trading
